class GetCard {}
GetCard.prototype.contentText = [
  {
    title: "TÜRK MİTOLOJİSİ",
    description:
      "Türk mitolojisi, tarihi Türk halklarının inanmış oldukları mitolojik bütüne verilen isimdir. Eski efsaneler, Türk halklarının eski ortak inancı Tengricilikten ögeler taşımaktan ziyade sosyal ve kültürel temalarla doludur. Bunların bazıları sonradan İslâmî ögeler ile değiştirilmiştir. Dünyanın en eski edebi belgelerinden biri olarak geçen Dede Korkut destanlarının orijinal yapıtları, Vatikan ve Dresden kütüphanelerinde bulunmaktadır. Ege ve Anadolu Uygarlığı mitolojisi ile benzerlikler taşımaktadır. Türkler, birçok medeniyet kurmuş, medeniyetlere efendilik yapmış, çağlar açmış, çağlar kapamış. Peki Türklerin kültürel birikiminin yansıması olamaz mı? Türk Mitolojisi, diğer mitolojilere örnek ve model kaynağı olmuştur. Türk mitolojisi, diğer ulusların mitolojisini aratmayacak kadar zengin ve esrarengizdir. Ne yazık ki, Türk tarihinde mitolojik kültür ve birikimimiz yok edilmeye çalışılmıştır. Türk Mitolojisini Dünya’ya yeteri kadar aktaramadığımız ve anlatamadığımız için de Eski Yunan, Mısır, İkandinav ve Kelt gibi kültürlerin mitolojisi popüler olmuştur. Ancak Türk Mitolojisi bu kültürlerin hepsinden eskidir. Diğer mitolojik kültürler Türk Mitolojisinden birçok şeyi almış ve kendilerininmiş gibi yansıtmışlardır. Bu yansımayı halen görmek mümkündür. ",
  },
];
GetCard.prototype.card = [
  {
    title: "ÖD TENGRİ.",
    description:
      "Eski Türklerin mitolojik söylencelerinde Öd Tengri zaman tanrısıdır. Hakkında en az bilgiye sahip olduğumuz tanrılardan biri olmakla birlikte Göktürk Kağanlığının Kültigin yazıtında  'Öd Tengri aysar kişi oglı kop ölgeli törümiş' cümlesiyle anılmıştır. Bu metnin günümüz Türkçesindeki karşılığı  ' Zaman tanrısı buyurur, kişioğlu hep ölmek için türemiş' biçiminde çevrilmektedir. Bu gönderme Öd Tengri'in zaman tanrısı olmasının yanı sıra buyruklarıyla insan yaşamının sınırlarını belirleme gücüne sahip bir kader tanrısı olarak tanımlanabileceğini göstermektedir. Zamanın ve kaderin sahipliği tüm dünya mitoslarında tartışmalı bir konudur. Sanılanın aksine Antik Grekler söz konusu kişilerin alın yazısı olduğunda oldukça kaderci bir toplumdu. Olimposun Hiç bir tanrısı ip eğiren zaman tanrıçalarının iradesine karşı gelemezdi. İskandinav mitolojisinde ise ip eğiren kadınlar karşımıza Nornlar adıyla çıkmaktadır. Her daim üç kişi olmalarının sebebi geçmiş, şimdiki ve gelecek zamanı temsil etmeleridir.Türk mitolojisinde ise zamanın akışı Gök çarkının çevrilmesi ile ilişkilidir. Gündüzün yerini geceye bırakışı ve gecenin gündüz tarafından sonsuza dek kovalanışı Uygur mitlerinde bir  çift su ejderi tarafından gerçekleştirilmektedir. ",
    imgUrl: "./css/img/ödtengri.jpg",
  },
  {
    title: "ERLİK HAN",
    description:
      " Eski Türklerin mitolojik söylencelerinde Erlik Han yeraltı dünyasının hakimi, körmöslerin demonik efendisi ve Reenkarnasyon çarkının bekçisidir. Türk mitolojisi ve halk biliminde Erlik hakkında en fazla bilgi sahibi olduğumuz tanrılardan biridir. Türkler Ural ve Sibirya ormanlarında görece izole yaşadıkları dönemlerde Erlik 'Yerlik' adında bir yer iyesi olarak kutsanıyordu. Henüz bir kötücül tanrı, bir yeraltı dünyası konsepti gelişmemişti. Türkler arasında devlet teşkilatının gelişimi ve iş bölümünün derinleşmesi ile beraber panteonun başına egemen savaş aristokrasisinin tanrısı Ülgen geçince Erlik önce yer iyeliğinden koparak bir ölüm tanrısına  sonra da yeraltının hakimi olan karanlıklar tanrısına dönüştü. Ülgen'in sahip olduğu güçlerin tamamına sahip olmakla birlikte onun tam karşıtı değerleri temsil ediyordu. Maaday Kara destanında görüldüğü gibi Ülgen'in temsil ettiği ak düzene karşı Erlik'in kara düzeni gösterilir.Mitler ve efsanelerde Erlik tüm Tengrileri yaratan ata Tengri Kayrakan'ın ilk oğludur. Babasının düzenine karşı kabaran iştahını bastıramadığından onun tahtına göz dikmiş, başaramayınca kendi kara düzenini kurmak için işe koyulmuştur.",
    imgUrl: "./css/img/erlik.jpg",
  },
  {
    title: "YARLIK",
    description:
      " Eski Türklerin mitolojik söylencelerinde Yarlık Kök Tengriden kut alarak tahta çıkan Kağanın buyruğudur. Kut kişiye tanrılar tarafından bahşedilen ve uzun ömür, şans ve liderlik karizması veren majik bir güçtür. Kağanın buyruğu olduğundan zamanla buyruğun kendisi kişilik kazanmış ve devlet otoritesinin temsil eden dişil bir figüre dönüşmüştür. Halk nezdinde Kimin yaşayıp kimin öleceğine karar veren en üst düzey makamla özdeşleştiği için belki de Yarlık'ı en iyi tanımlayan ifade ' Devlet Ana ' olmuştur. Yarlık sözcüğü etimolojik bakımdan Türkçe'den Moğolcaya geçen bir sözcüktür. Siyasi ve mitolojik olarak iki kullanımı bulunmaktadır. Siyasi etimolojide Devlet teşkilatının başındaki egemenin bağlaşıklarına yolladığı buyruklar bütünü olarak tanımlanabilir.Yarlıklar Türk-Moğol idaresi ile o kadar özdeşleşmiştir ki dönem kaynaklarında Rus Knezlerinin bağlı oldukları Cengizi Hanedanına yolladıkları mektuplardan yarlık olarak bahsedilmektedir. Bu dönemde yazılan Yarlıklar Uygur üslubunun etkisini taşır.Mitolojik bakımdan Yarlık eski Türkçede parlama eylemini karşılayan 'yarlama' sözcüğünden türemiştir ve parlak ışık anlamına gelir. ",
    imgUrl: "./css/img/yarlık.jpg",
  },
  {
    title: "ALP ER TUNGA",
    description:
      "Tunga sözcüğü aslında leopar cinsinden yırtıcı bir hayvanın adıdır. Bir yiğitlik simgesi olarak alplara isim diye verilir. Uzun saçlı olmak Tunga’yı çağrıştırdığı için alplar saç uzatırlar. Ayrıca cengaverler yırtıcı hayvanların özellikle de aslan, kaplan, pars, tunga gibi hayvanların postlarını giyerler. Bu postlar savaşçılığın sembolüdür. Alpar Tunga Han, yanında iki tane tunga (leopar) ile resmedilir, sırtında da bir post vardır, postun dişleri başının üzerinden görünür. Tüm Türk dünyasında olduğu kadar İran ve Ortadoğu halklarının pek çoğu tarafından tanınır. Selçukluların 33 atasından biri olarak sayılır. Yeraltındaki 100 sütunlu demir sarayında yaşar. Alpar sıfatıyla anılır. İran mitolojisinde adı Afrasyab olarak geçer.Yaşamıyla ilgili bilgiler efsanelere dayanan Alp Er Tunga'nın, Turancılarca Türklerin eski atalarının soyundan geldiği öne sürülür. Ayrıca, Divân-ı Lügati't-Türk'te ve Kutadgu Bilig'de, İran destanı Şehnâme'nin kahramanlarından Efrasiyab (Afrasyab)'la aynı kişi olduğu belirtilir. Şehname'ye göre İran - Turan savaşları sırasında Zaloğlu Rüstem ile giriştiği mücadele sırasında pusuya düşürülüp öldürülmüştür. Öldürülmesiyle ilgili Alp Er Tunga Sagusu, Divân-ı Lügati't-Türk'ün çeşitli yerlerinde örnek metin olarak verildiği söylenmektedir.",
    imgUrl: "./css/img/alpertunga.jpg",
  },
  {
    title: "AY DEDE",
    description:
      "Eski Türklerin mitolojik söylencelerinde Ay dede tanrısal güçlere sahip iki göksel küreden biridir. Halk anlatılarında annesi ve Ülgen'in eşi olan Kün-eş'e(Güneş) nazaran daha fazla iz bırakmıştır. Kıpçak Türklerinin anlatınlarında ilk insan Güneş ışığının beslediği kilden yaratılmıştır ve adı 'Ay Atamdır'. Doğumundan beri bir insan formunda hayal edilen Ay böylece kozmik düzen içinde Güneşin eril tamamlayıcısı olarak yerini almıştır. Ay dedeyi doğuranın ve ona ışığını bahşedenin Güneş olduğu anlaşılıyor. Annesinden miras aldığı yaratım gücünü kullanan Ay dedenin ışığıyla gerek sıradan insanları gerek mitolojik kahramanların eşlerini hamile bırakabildiğini görüyoruz. Ay eski Türkçede 'Yaruk' adı verilen ışıkla özdeşleşmiş büyü enerjisinin sahiplerinden biri olarak görüldüğünden Hun kralları gündoğumunda çadırlarından çıkarak güneşin önünde eğilir ve kımız saçısı yapar, geceyarısı olduğunda ise aynı işlemi Ay için tekrar ederlerdi.Uygur fal kitabı Irk bitigde Ay dede  'Ay Tengri' olarak geçmektedir. Sibirya Türk masallarında tanrıların göğe iki disk koyduğu, birinden ateş diğerinden su elementi doğduğu anlatılıyor. ",
    imgUrl: "./css/img/aydede.jpg",
  },
  {
    title: "MERGEN TENGRİ",
    description:
      "Eski Türklerin mitolojik söylencelerinde Mergen Tengri bilgelik tanrısıdır. Kendisine Anohin, Radloff ve Harva'nın aktardığı Sibirya Türklerine ait Şaman yakarışları dışında hemen hiç bir anlatıda rastlanmaz. Alkış adı verilen bu Şaman dualarında ise Mergen yaz yağmurları işe özdeşleşmiş bir bolluk tanrısı olarak karşımıza çıkar. Mavi ve Beyaz renklerle simgelenir ve doru ata binen bir okçu olarak betimlenirdi. Kayra Kan'ın yedi oğlundan biri ve Fırtına tengrisi Ülgen'in kardeşidir. Astrolojik sistemde Merküre denk gelir ve Türkler de diğer toplumların mitoslarında görüldüğü gibi bu gezegeni gizli bilgiler ve habercilik ile özdeşleştirirler. Emel Esin'in aktarımına göre Mergen bir tür alp ocağı ünvanıdır ve keskin nişancı okçulardan bu adla bahsedilir. Bu okçular yeteneklerinin takdir edilmesi sayesinde miğferlerine bir çift kuş kanadı takma hakkını kazanırlar. Kuş kanatları göksel bir soya işaret eder ve kutlu kabul edilirdi. Mergen Tengri'nin adının kökeni de kendisinin okçulara atfedilen bilgelik, ustalık ve sabır erdemlerine sahip olmasıyla ilişkili olabilir. Mısır'ın bilgelik tanrısı olan Thot bir kuş formundadır ve Yunan panteonunun Hermes'i gibi tanrıların haberciliğine soyunur ve ölümlülere gizli sırlar bahşeder. Hermes'in sandaletindeki kanatlar da kendisinin göksel soyuna işaret etmektedir.",
    imgUrl: "./css/img/mergen.jpg",
  },
  {
    title: "KAPGAN KAGAN",
    description:
      "Kapgan Kağan. II. Göktürk Kağanlığının kurucusu İlteriş'in küçük kardeşi olan Kapgan, 692 yılında ağabeyinin ölümünden sonra tahta çıkmıştır. Jean-Paul Roux' ya göre Kapgan adının anlamı 'Kapağan' olarak da ifade edilen yaban domuzudur. Eski Türk toplumunun omurgasını oluşturan ve Türklerin militarist oligarşik devlet aygıtının da temeli olan kurum alp teşkilatıydı. Alplar, çocuk yaştaki kız ve erkeklerin gruplara ayrılarak birbirlerine zimmetlendiği, komünal bir yaşam biçiminin hüküm sürdüğü ve kan kardeşliğine dayanan bir kurumdu. Profesyonel savaşçı ve örgütçü olarak yetiştirilen bu çocuklar eğitimleri sırasında Şamanist bir ritüel aracılığıyla kutsal hayvanlardan biri ile ilişkilendirilirlerdi. Kişi ilişkilendiği hayvanın majik güçlerine sahip olur ve mizacını bu hayvanın temsil ettiği kozmik sırlara göre oluştururdu. Nitekim Kapgan(Yaban Domuzu), Böri(Kurt), Buka(Yılan-ejderha) ve Tong(Kaplan)  gibi adlar eski Türk liderleri arasında yaygındır. Bu kült daha popüler haliyle Vikingler arasındaki Ulfsarkr (kurt adam) ve Berserkyr(ayı adam) kültlerinin karşılığıdır. Bir fikir vermesi bakımından Kıpçak Hanı Bonyak'ın savaş sırasında bir kurt gibi uluduğu rivayet edilir. Bunun yanı sıra Kapganın diğer adının Türkçede Şamanın karşılığı olan 'Bögü' olması Kapgan'ın sadece bir alptan öte şamanik bir yönünün olması ihtimalini güçlendiriyor.",
    imgUrl: "./css/img/kapgan.jpg",
  },
  {
    title: "İLBİLGE HATUN",
    description:
      "İlbilge Hatun. 8.yüzyılda Göktürk devletini küllerinden dirilten efsanevi lider İlteriş Kağan'ın eşi olan İlbilge Hatun aynı zamanda meşhur Bilge Kağanın annesidir. Orhun vadisinde Bilge Kağanın onuruna dikilen taş yazıtta kendisinden bahsedilir. Bilge Kağan bu yazıtta Gök ve yersuyu kontrol eden tanrısal güçlerin perişan haldeki Türkleri dizlerinin üstüne doğrultmak için annesi İlbilge Hatunu ve babası İlteriş'i desteklediklerinden bahseder. Bilge Kağanın bu söylemi Türk panteonunun üst dünyadaki tanrısal çifti olan ana tanrıça Umay ve fırtına tanrısı arketipini karşılayan Kök Tengri'nin birlikteliğine referans verir. Türkler kendi siyasi liderlerinden bahsettiklerinde Kağan ve Hatunu Kök Tengri ve Umay'ın yeryüzündeki uzantısı, tanrısal düzenin orta dünyadaki koruyucusu olarak görürlerdi. Mitolojik terimlerle konuşmak gerekirse bu iki lider Tengrilerin avatarlarıydı. Bu yüzden Bilge Kağan 'Tengri teg tengride bolmış Türük Bilge Kağan' yani göğe benzer ve gökten olmuş Türk Bilge Kağan olarak tanımlanmış, İlbilge Hatundan ise yazıtlarda 'Umay gibi annem... ' olarak bahsedilmiştir. Göktürk devletini yıllar boyunca eşi İlteriş'le birlikte yöneten İlbilge Hatun İlteriş ve Tonyukuk'un Güney Sibirya' ya gerçekleştirdiği bir sefer sırasında yaşamını yitirmiştir. Ölümünün nasıl gerçekleştiği konusunda bir veri bulunmamaktadır.",
    imgUrl: "./css/img/ilbilge.jpg",
  },
  
];
